### ISSUE TITLE
Test Explorer UI updated version (2.20.2) makes Behave Test Explorer not work

### ISSUE THREAD

**Issue by rdaquina** [YouneselBarnoussi/vscode-BDD-Python-test-adapter#1]
Hi,

The new Text Explorer UI update (2.20.2) is impacting Behave Test Explorer on VSCode. In this version the extension is not working properly.

Best regards,

**Comment by YouneselBarnoussi** [comment]
Thanks for submitting the issue, I will have a look at it. For now, if you want to keep using the extension you can downgrade the test explorer UI version in your marketplace.

**Comment by lorthirk** [comment]
Here's a log from the debugger:

```
rejected promise not handled within 1 second: Error occurred during process execution: Error: spawn cd && behave ENOENT
/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js:5
rejected promise not handled within 1 second: Error: Error occurred during process execution: Error: spawn behave ENOENT
/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js:5
stack trace: Error: Error occurred during process execution: Error: spawn behave ENOENT
	at behaveTestRunner.<anonymous> (/Users/claudio.mezzasalma/dev/git/lorthirk/vscode-BDD-Python-test-adapter/out/behaveTestRunner.js:29:23)
	at Generator.throw (<anonymous>)
	at rejected (/Users/claudio.mezzasalma/dev/git/lorthirk/vscode-BDD-Python-test-adapter/node_modules/tslib/tslib.js:108:69)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by lorthirk** [comment]
And this is the JS Object contained in the `error` event at `processExecution:53`

```
{
    errno: -2,
    code: "ENOENT",
    syscall: "spawn behave",
    path: "behave",
    spawnargs: [
      "--dry-run",
      undefined,
    ],
    vslsStack: [
      {
      },
      {
      },
      {
      },
    ],
  }
```

**Comment by YouneselBarnoussi** [comment]
Thanks for posting the logs, I am not able to recreate them. Would you be able to provide a sample project that causes this error?

**Comment by lorthirk** [comment]
It's a simple project with `pipenv` to manage the dependencies, and `behave` installed as a dev dependency. The `ENOENT` error makes me think that the command is spawn outside of the environment.
[python-playground.tar.gz](https://github.com/YouneselBarnoussi/vscode-BDD-Python-test-adapter/files/6725555/python-playground.tar.gz)

**Comment by YouneselBarnoussi** [comment]
I have been trying out the sample project that you have posted and it works completely fine for me on multiple versions of Test Explorer UI. I think it might be your working environment that is causing the bug, could you give me any more information about that?

**Comment by lorthirk** [comment]
What information do you need exactly?

**Comment by tyrius02** [comment]
I'm having virtually the same issue. I use Anaconda to manage my environments.

Here are my repro steps. Note, you must not have behave anywhere in your PATH.
1. Install Anaconda (I use mambaforge from https://github.com/conda-forge/miniforge)
The installer updates .bashrc on Linux; you'll need to start your terminal as a login shell or source ~/.bashrc (this assume you're using bash)
If you're on Windows the installer will add a start menu entry which you can use to open a console window set up for Anaconda
2. Create a new environment
I use mamba, but you can use conda, just swap one for the other
`mamba create -y -n repro -c conda-forge --strict-channel-priority behave`
3. Change the current directory to the location of a project w/ behave tests
4. Launch VS Code from here (simply type `code` in the console window)
5. Install the extension
6. Reload the window (CTRL + R)
7. View the Runtime Status of the Behave Test Explorer extension.
You should see `Error occurred during process execution: Error: spawn behave ENOENT`

If you activate the environment from the console window (`conda activate repro`) and then launch VS Code the extension works just fine.

I think the problem is the extension blindly assumes behave is available on the PATH when VS Code is launched. I wonder if there's a way to leverage Microsoft's Python extension and use the current Python interpreter (you can invoke behave via `python -m behave`).

**Comment by YouneselBarnoussi** [comment]
Thanks for your step by step explanation @tyrius02 , For now, I implemented the invocation you suggested (`python -m behave`). If this did not fix it, let me know and I will try to put this on the top of my list.

I abandoned this extension for a while but in the coming month, I will try to update this extension with more improvements.
